# -*- coding: utf-8 -*-
"""github.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Sx6ME5FRoFxhAQK210gw4Q9LgYWf7Qb
"""

import requests

def get_github_projects(github_link):
    # Extract the GitHub username from the URL
    github_username = github_link.split('/')[-1]

    # GitHub API endpoint for fetching user's repositories
    api_url = f"https://api.github.com/users/{github_username}/repos"

    # Send a GET request to the API
    response = requests.get(api_url)

    if response.status_code == 200:
        # If the response is successful, parse the JSON data
        repositories = response.json()

        # Extract project names (repositories)
        project_names = [repo['name'] for repo in repositories]

        if project_names:
            print(f"Projects by {github_username}:")
            for project in project_names:
                print(f"- {project}")
        else:
            print(f"No public repositories found for {github_username}.")
    else:
        print(f"Failed to fetch data. Status code: {response.status_code}")


# Example usage
github_link = "https://github.com/VamshiVasala"  # Replace with actual GitHub profile link
get_github_projects(github_link)